// ============================================================
// JARVIS — Realistic Mock Data
// Used when API keys are not configured
// ============================================================

import type {
  NewsArticle,
  CalendarEvent,
  EmailMessage,
  CryptoQuote,
  PortfolioItem,
  NetWorthSnapshot,
} from '@/types'

export const MOCK_NEWS: NewsArticle[] = [
  {
    id: '1',
    title: 'OpenAI Releases GPT-5 with 10x Reasoning Improvements Over GPT-4',
    source: 'TechCrunch',
    url: 'https://techcrunch.com',
    publishedAt: new Date(Date.now() - 1000 * 60 * 23).toISOString(),
    description: 'OpenAI\'s latest flagship model demonstrates unprecedented reasoning capabilities, passing bar exams and medical boards with near-perfect scores.',
    category: 'llms',
  },
  {
    id: '2',
    title: 'Google DeepMind\'s AlphaFold 3 Can Now Predict Any Biomolecule Structure',
    source: 'MIT Technology Review',
    url: 'https://technologyreview.com',
    publishedAt: new Date(Date.now() - 1000 * 60 * 87).toISOString(),
    description: 'The latest version of AlphaFold extends beyond proteins to DNA, RNA, and small molecules, potentially revolutionizing drug discovery.',
    category: 'research',
  },
  {
    id: '3',
    title: 'Anthropic Launches Claude 4 with Constitutional AI 2.0',
    source: 'Wired',
    url: 'https://wired.com',
    publishedAt: new Date(Date.now() - 1000 * 60 * 142).toISOString(),
    description: 'Claude 4 introduces Constitutional AI 2.0, with dramatically improved safety, nuanced reasoning, and a 500k context window.',
    category: 'llms',
  },
  {
    id: '4',
    title: 'New Open-Source LLM Beats GPT-4 at Coding Tasks While Running on Laptop',
    source: 'Hacker News',
    url: 'https://news.ycombinator.com',
    publishedAt: new Date(Date.now() - 1000 * 60 * 215).toISOString(),
    description: 'A team of researchers from MIT have released a 7B parameter model that outperforms GPT-4 on HumanEval using a novel training technique.',
    category: 'tools',
  },
  {
    id: '5',
    title: 'AI Agents Are Replacing Junior Developers — But Creating New Senior Roles',
    source: 'The Verge',
    url: 'https://theverge.com',
    publishedAt: new Date(Date.now() - 1000 * 60 * 378).toISOString(),
    description: 'As AI coding assistants grow more capable, the market for senior engineers who can direct and validate AI output is surging.',
    category: 'all',
  },
  {
    id: '6',
    title: 'Mistral AI Releases Mixture-of-Experts Model with 141B Parameters',
    source: 'VentureBeat',
    url: 'https://venturebeat.com',
    publishedAt: new Date(Date.now() - 1000 * 60 * 520).toISOString(),
    description: 'Mistral\'s new MoE architecture activates only 39B parameters per forward pass while achieving performance rivaling much larger dense models.',
    category: 'research',
  },
  {
    id: '7',
    title: 'Apple Integrates On-Device LLM in iOS 18 for Fully Private AI Features',
    source: 'MacRumors',
    url: 'https://macrumors.com',
    publishedAt: new Date(Date.now() - 1000 * 60 * 680).toISOString(),
    description: 'Apple\'s new on-device AI processes requests entirely locally with no data leaving your phone, powered by a custom 3B parameter model.',
    category: 'tools',
  },
]

export const MOCK_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: '1',
    title: 'Daily Standup',
    start: new Date(new Date().setHours(9, 0, 0, 0)).toISOString(),
    end: new Date(new Date().setHours(9, 15, 0, 0)).toISOString(),
    allDay: false,
    color: '#00D4FF',
    meetingUrl: 'https://meet.google.com',
  },
  {
    id: '2',
    title: 'Product Review — Q2 Roadmap',
    start: new Date(new Date().setHours(11, 0, 0, 0)).toISOString(),
    end: new Date(new Date().setHours(12, 30, 0, 0)).toISOString(),
    allDay: false,
    color: '#FFB830',
    location: 'Conference Room A',
    meetingUrl: 'https://zoom.us/j/123456789',
  },
  {
    id: '3',
    title: 'Lunch with Alex',
    start: new Date(new Date().setHours(13, 0, 0, 0)).toISOString(),
    end: new Date(new Date().setHours(14, 0, 0, 0)).toISOString(),
    allDay: false,
    color: '#00FF88',
    location: 'The Grid Café',
  },
  {
    id: '4',
    title: 'Architecture Deep Dive',
    start: new Date(new Date().setHours(15, 30, 0, 0)).toISOString(),
    end: new Date(new Date().setHours(17, 0, 0, 0)).toISOString(),
    allDay: false,
    color: '#FF3B5C',
    meetingUrl: 'https://meet.google.com/abc-defg-hij',
  },
  {
    id: '5',
    title: 'Sprint Planning',
    start: new Date(new Date(Date.now() + 86400000).setHours(10, 0, 0, 0)).toISOString(),
    end: new Date(new Date(Date.now() + 86400000).setHours(11, 30, 0, 0)).toISOString(),
    allDay: false,
    color: '#00D4FF',
    meetingUrl: 'https://zoom.us/j/987654321',
  },
  {
    id: '6',
    title: 'Team Social Hour',
    start: new Date(new Date(Date.now() + 172800000).setHours(17, 0, 0, 0)).toISOString(),
    end: new Date(new Date(Date.now() + 172800000).setHours(18, 30, 0, 0)).toISOString(),
    allDay: false,
    color: '#9B59B6',
  },
]

export const MOCK_EMAILS: EmailMessage[] = [
  {
    id: '1',
    threadId: 'thread1',
    from: 'Sarah Chen',
    fromEmail: 'sarah.chen@acmecorp.com',
    subject: 'URGENT: Q2 Budget Review — Action Required by EOD',
    preview: 'Hi, we need your sign-off on the revised budget figures before the board meeting tomorrow...',
    receivedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    isRead: false,
    isImportant: true,
    gmailUrl: 'https://mail.google.com',
  },
  {
    id: '2',
    threadId: 'thread2',
    from: 'Stripe',
    fromEmail: 'billing@stripe.com',
    subject: 'Invoice #INV-2024-0892 — $4,200.00 due',
    preview: 'Your invoice for the month of March is ready. Payment is due by April 15th...',
    receivedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    isRead: false,
    isImportant: true,
    gmailUrl: 'https://mail.google.com',
  },
  {
    id: '3',
    threadId: 'thread3',
    from: 'Marcus Rivera',
    fromEmail: 'marcus@venturecap.io',
    subject: 'Meeting request — potential partnership discussion',
    preview: 'We\'ve been following your work and would love to schedule a call to discuss...',
    receivedAt: new Date(Date.now() - 1000 * 60 * 128).toISOString(),
    isRead: false,
    isImportant: true,
    gmailUrl: 'https://mail.google.com',
  },
  {
    id: '4',
    threadId: 'thread4',
    from: 'GitHub',
    fromEmail: 'noreply@github.com',
    subject: '[jarvis-dashboard] New deployment — production',
    preview: 'Your deployment to production was successful. Build #142 passed all checks...',
    receivedAt: new Date(Date.now() - 1000 * 60 * 203).toISOString(),
    isRead: true,
    isImportant: false,
    gmailUrl: 'https://mail.google.com',
  },
  {
    id: '5',
    threadId: 'thread5',
    from: 'Lena Schmidt',
    fromEmail: 'lena@clientco.de',
    subject: 'Client feedback on Phase 1 — mostly positive',
    preview: 'The team has reviewed the initial deliverables and we have a few notes. Overall very impressed...',
    receivedAt: new Date(Date.now() - 1000 * 60 * 340).toISOString(),
    isRead: false,
    isImportant: true,
    gmailUrl: 'https://mail.google.com',
  },
]

export const MOCK_CRYPTO: CryptoQuote[] = [
  {
    id: 'bitcoin',
    symbol: 'BTC',
    name: 'Bitcoin',
    current_price: 67842.50,
    price_change_percentage_24h: 2.34,
    sparkline_in_7d: {
      price: [62100, 63400, 64200, 63800, 65100, 66400, 67842]
    },
    market_cap: 1330000000000,
  },
  {
    id: 'ethereum',
    symbol: 'ETH',
    name: 'Ethereum',
    current_price: 3521.80,
    price_change_percentage_24h: -0.87,
    sparkline_in_7d: {
      price: [3450, 3380, 3420, 3560, 3490, 3540, 3521]
    },
    market_cap: 423000000000,
  },
  {
    id: 'solana',
    symbol: 'SOL',
    name: 'Solana',
    current_price: 182.40,
    price_change_percentage_24h: 5.12,
    sparkline_in_7d: {
      price: [155, 160, 168, 172, 175, 178, 182]
    },
    market_cap: 81000000000,
  },
]

export const MOCK_PORTFOLIO_ITEMS: PortfolioItem[] = [
  {
    id: '1',
    user_id: 'mock',
    ticker: 'AAPL',
    type: 'stock',
    name: 'Apple Inc.',
    quantity: 25,
    manual_value: null,
    created_at: new Date().toISOString(),
    currentPrice: 189.50,
    change24h: 1.23,
    totalValue: 4737.50,
    sparkline: [182, 184, 186, 185, 188, 187, 189],
  },
  {
    id: '2',
    user_id: 'mock',
    ticker: 'MSFT',
    type: 'stock',
    name: 'Microsoft Corp.',
    quantity: 15,
    manual_value: null,
    created_at: new Date().toISOString(),
    currentPrice: 415.20,
    change24h: -0.45,
    totalValue: 6228.00,
    sparkline: [420, 418, 416, 419, 417, 416, 415],
  },
  {
    id: '3',
    user_id: 'mock',
    ticker: 'BTC',
    type: 'crypto',
    name: 'Bitcoin',
    quantity: 0.5,
    manual_value: null,
    created_at: new Date().toISOString(),
    currentPrice: 67842.50,
    change24h: 2.34,
    totalValue: 33921.25,
    sparkline: [62100, 63400, 64200, 63800, 65100, 66400, 67842],
  },
  {
    id: '4',
    user_id: 'mock',
    ticker: 'BANK',
    type: 'manual',
    name: 'Chase Savings',
    quantity: 1,
    manual_value: 24500,
    created_at: new Date().toISOString(),
    currentPrice: 24500,
    change24h: 0,
    totalValue: 24500,
    sparkline: [24500, 24500, 24500, 24500, 24500, 24500, 24500],
  },
]

export const MOCK_NET_WORTH_HISTORY: NetWorthSnapshot[] = Array.from({ length: 12 }, (_, i) => ({
  id: String(i),
  user_id: 'mock',
  total_value: 80000 + Math.random() * 10000 + i * 2000,
  snapshot_date: new Date(Date.now() - (11 - i) * 30 * 24 * 60 * 60 * 1000)
    .toISOString()
    .split('T')[0],
  created_at: new Date().toISOString(),
}))
